import type { Metadata } from "next";
import NavLinks from "./components/navlinks";
import "./globals.css";

export const metadata: Metadata = {
  title: "Super Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <NavLinks/>
        {children}
      </body>
    </html>
  );
}
